import type { AgentDefinition } from '@/types'

// Agents are pre-generated by `npm run parse-agents`
// Vite handles JSON imports natively; the try/catch handles missing file gracefully
let agentsData: AgentDefinition[] = []

try {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const mod = (await import('../data/agents.json')) as { default: AgentDefinition[] }
  agentsData = mod.default
} catch {
  console.warn('agents.json not found — run `npm run parse-agents` to generate it')
}

export const agents: AgentDefinition[] = agentsData

/** Returns agents grouped by category */
export function agentsByCategory(): Record<string, AgentDefinition[]> {
  const grouped: Record<string, AgentDefinition[]> = {}
  for (const agent of agents) {
    if (!grouped[agent.category]) grouped[agent.category] = []
    grouped[agent.category].push(agent)
  }
  return grouped
}

/** Friendly display name for a category slug */
export function categoryLabel(slug: string): string {
  const labels: Record<string, string> = {
    engineering: 'Engineering',
    design: 'Design',
    marketing: 'Marketing',
    product: 'Product',
    'project-management': 'Project Mgmt',
    support: 'Support',
    testing: 'Testing',
    'spatial-computing': 'Spatial Computing',
    'game-development': 'Game Dev',
    specialized: 'Specialized',
    strategy: 'Strategy',
  }
  return labels[slug] ?? slug
}

export function getAgent(id: string): AgentDefinition | undefined {
  return agents.find((a) => a.id === id)
}
